class Product < ActiveHash::Base
  self.data = [
    {id: 1, name: 'きゅうり'}, {id: 2, name: 'とまと'}, {id: 3, name: '袋サラダ'},
    {id: 4, name: 'オクラ'}, {id: 5, name: 'たまねぎ'}, {id: 6, name: 'グリーンアスパラ'},
    {id: 7, name: 'ミニトマト'}, {id: 8, name: 'キャベツ'}, {id: 9, name: 'なす'},
    {id: 10, name: '小松菜'}, {id: 11, name: 'サニーレタス'}, {id: 12, name: 'しめじ'},
    {id: 13, name: 'レタス'}, {id: 14, name: '長芋'}, {id: 15, name: 'ピーマン'},
    {id: 16, name: 'メークイン'}, {id: 17, name: '洋人参'}, {id: 18, name: 'えのき茸'},
    {id: 19, name: 'もやし'}, {id: 20, name: 'しょうが'}, {id: 21, name: 'カイワレ'},
    {id: 22, name: '青ねぎ'}, {id: 23, name: 'ベビーリーフ'}, {id: 24, name: '大根'},
    {id: 25, name: 'カップサラダ'}, {id: 26, name: 'マッシュルーム'}, {id: 27, name: 'ブロッコリー'},
    {id: 28, name: 'ごぼう'}, {id: 29, name: 'まいたけ'}, {id: 30, name: 'ナンキン'},
    {id: 31, name: '大葉'}, {id: 32, name: '白ネギ'}, {id: 33, name: '生椎茸'},
    {id: 34, name: '枝豆'}, {id: 35, name: 'にら'}, {id: 36, name: 'スイートコーン'},
    {id: 37, name: 'その他葉菜'}, {id: 38, name: '白菜'}, {id: 39, name: '水煮筍'},
    {id: 40, name: '刻みネギ'}, {id: 41, name: 'エリンギ'}, {id: 42, name: 'なめこ'},
    {id: 43, name: '簡便セット野菜'}, {id: 44, name: 'その他水物加工'}, {id: 45, name: 'セロリ'},
    {id: 46, name: 'にがうり'}, {id: 47, name: 'ミョウガ'}, {id: 48, name: 'にんにく'},
    {id: 49, name: 'ドレッシング'}, {id: 50, name: 'さつま芋'}, {id: 51, name: '蓮根'},
    {id: 52, name: '馬鈴薯'}, {id: 53, name: 'カラーピーマン'}, {id: 54, name: 'グリーンボール'},
    {id: 55, name: 'ソース'}, {id: 56, name: '里芋'}, {id: 57, name: 'インゲン豆'},
    {id: 58, name: 'チンゲンサイ'}, {id: 59, name: 'ししとう'}, {id: 60, name: 'その他レタス類'},
    {id: 61, name: '乾燥野菜'}, {id: 62, name: 'スナップエンドウ'}, {id: 63, name: 'ほうれん草'},
    {id: 64, name: '春菊'}, {id: 65, name: 'グリーンピース'}, {id: 66, name: 'その他山菜'},
    {id: 67, name: 'カリフラワー'}, {id: 68, name: 'ズッキーニ'}, {id: 69, name: '冬瓜・瓜類'},
    {id: 70, name: '青梅'}, {id: 71, name: 'らっきょう'}, {id: 72, name: '生筍'},
    {id: 73, name: 'その他菌茸'}, {id: 74, name: 'キウイフルーツ'}, {id: 75, name: 'レギュラーバナナ'},
    {id: 76, name: '高糖度バナナ'}, {id: 77, name: '桃'}, {id: 78, name: '巨峰'},
    {id: 79, name: 'ピオーネ'}, {id: 80, name: 'デラウェア'}, {id: 81, name: 'シャインマスカット'},
    {id: 82, name: 'ニューベリー'}, {id: 83, name: 'その他青系ぶどう'}, {id: 84, name: '甲斐路ぶどう'},
    {id: 85, name: 'その他黒系ぶどう'}, {id: 86, name: '輸入ぶどう'}, {id: 87, name: 'スイカ'},
    {id: 88, name: 'アボカド'}, {id: 89, name: '現物ギフト'}, {id: 90, name: '梨'},
    {id: 91, name: 'ラ・フランス'}, {id: 92, name: 'りんご'}, {id: 93, name: '無花果'},
    {id: 94, name: 'グレープフルーツ'}, {id: 95, name: '生パイン'}, {id: 96, name: '焼き芋'},
    {id: 97, name: 'カットフルーツ'}, {id: 98, name: 'プラム'}, {id: 99, name: 'オレンジ'},
    {id: 100, name: 'メロン'}, {id: 101, name: 'さくらんぼ'}, {id: 102, name: 'レモン'},
    {id: 103, name: 'ハウスみかん'}, {id: 104, name: 'ドライフルーツ'}, {id: 105, name: 'マンゴー'},
    {id: 106, name: 'ジュース・ゼリー'}, {id: 107, name: 'いちご'}, {id: 108, name: 'ナッツ'},
    {id: 109, name: '柿'}, {id: 110, name: '干し柿'}, {id: 111, name: 'みかん'},
    {id: 112, name: 'デコポン'}, {id: 113, name: 'ポンカン'}, {id: 114, name: 'はっさく'},
    {id: 115, name: 'いよかん'}, {id: 116, name: '金柑'}, {id: 117, name: 'その他柑橘'},
    {id: 118, name: '生栗'}, {id: 119, name: '甘栗'}, {id: 120, name: '輸入メロン'},
    {id: 121, name: '輸入チェリー'}
  ]
end