class Store < ActiveHash::Base
  self.data = [
    {id: 1, name: '丹波'}, {id: 2, name: '姫路'}, {id: 3, name: '井原'},
    {id: 4, name: '久世'}, {id: 5, name: '高梁'}, {id: 6, name:  '山陽'},
    {id: 7, name: '倉敷'}, {id: 8, name: '平島'}, {id: 9, name: '邑久'},
    {id: 10, name: '津山'}, {id: 11, name: '美作'}, {id: 12, name: '久米'},
    {id: 13, name: 'ウエストランド'}, {id: 14, name: 'LECT'}, {id: 15, name: '広島'},
    {id: 16, name: '廿日市'}, {id: 17, name: '呉'}, {id: 18, name: 'みゆき'},
    {id: 19, name: '安古市'}, {id: 20, name: '学園'}, {id: 21, name: '祇園'},
    {id: 22, name: '吉田'}, {id: 23, name: '五日市'}, {id: 24, name: '江田島'},
    {id: 25, name: '黒瀬'}, {id: 26, name: '松永'}, {id: 27, name: '蔵王'},
    {id: 28, name: '大竹'}, {id: 29, name: '竹原'}, {id: 30, name: '東広島'},
    {id: 31, name: '福山'}, {id: 32, name: 'サンモール'}, {id: 33, name: '阿賀'},
    {id: 34, name: '安浦'}, {id: 35, name: '安芸津'}, {id: 36, name: '己斐'},
    {id: 37, name: '沼田'}, {id: 38, name: '大竹新町'}, {id: 39, name: '西栄'},
    {id: 40, name: '川尻'}, {id: 41, name: '二葉の里'}, {id: 42, name: '八幡'},
    {id: 43, name: '八本松'}, {id: 44, name: '八木'}, {id:45, name: '尾道'},
    {id: 46, name: '府中'}, {id: 47, name: '出雲'}, {id: 48, name: '浜田'},
    {id: 49, name: '益田'}, {id: 50, name: '斐川'}, {id: 51, name: '江津'},
    {id: 52, name: 'YM浜田'}, {id: 53, name: '神西'}, {id: 54, name: 'ゆめシティ'},
    {id: 55, name: '宇部'}, {id: 56, name: '山口'}, {id: 57, name: '小野田'},
    {id: 58, name: '新南陽'}, {id: 59, name: '長府'}, {id: 60, name: '南岩国'},
    {id: 61, name: '防府'}, {id: 62, name: '柳井'}, {id: 63, name: '徳山'},
    {id: 64, name: '下松'}, {id: 65, name: '下関'}, {id: 66, name: '下関駅'},
    {id: 67, name: '三田尻'}, {id: 68, name: '南小野田'}, {id: 69, name: '高松'},
    {id: 70, name: '丸亀'}, {id: 71, name: '三豊'}, {id: 72, name: '木太'},
    {id:73, name: '徳島'}, {id: 74, name: '博多'}, {id: 75, name: '筑紫野'},
    {id: 76, name: '久留米'}, {id: 77, name: '大牟田'}, {id: 78, name: '行橋'},
    {id: 79, name: '南行橋'}, {id: 80, name: '宗像'}, {id: 81, name: '大川'},
    {id: 82, name: '遠賀'}, {id: 83, name: '八女'}, {id: 84, name: '柳川'},
    {id: 85, name: 'うきは'}, {id: 86, name: '小倉東'}, {id: 87, name: '新宮'},
    {id: 88, name: '福津'}, {id: 89, name: '城野'}, {id: 90, name: '筑後'},
    {id: 91, name: '青山'}, {id: 92, name: '佐賀'}, {id: 93, name: '武雄'},
    {id: 94, name: 'YMさが'}, {id: 95, name: '夢彩都'}, {id: 96, name: '別府'},
    {id: 97, name: '中津'}, {id: 98, name: '日田'}, {id: 99, name: 'はません'},
    {id: 100, name: '光の森'}, {id: 101, name: '八代'}, {id: 102, name: '大江'},
    {id: 103, name: '玉名'}, {id: 104, name: 'サンピアン'}, {id: 105, name: 'あらお'},
    {id: 106, name: '田崎'}, {id: 107, name: '松橋'}
  ]
end